version: '3'

services:
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

volumes:
  postgres:
    driver: local