version: '3'

services:
  app:
    build: .
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/investiment_platform_dev
      SECRET_KEY_BASE: aTnq/GCvShuNbwSVreSKdDb2GFr1d3o1ygRi3mdfDaYtRmXjRlJizqxM7l7LQ9SL
      PHX_HOST: "localhost"
    ports:
      - 4000:4000

  db:
    image: postgres:17.0
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@db:5432/investiment_platform_dev?sslmode=disable"

  redis:
    image: redis
    command: redis-server --requirepass admin
    volumes:
      - cache:/root/redis
    ports:
      - "6379:6379"

  redis-exporter:
    image: oliver006/redis_exporter:v1.6.0-alpine
    ports:
      - 9121:9121
    command:
      - '--redis.addr=redis://redis:6379'
      - '--redis.password=admin'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

volumes:
  postgres:
    driver: local
  cache:
    driver: local
